# Generated by Django 4.1.7 on 2023-04-03 10:37

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rights',
            name='right_number',
            field=models.IntegerField(default=0, validators=[system.models.group_rights_validator], verbose_name='Номер прав'),
            preserve_default=False,
        ),
    ]
