# Generated by Django 4.1.7 on 2023-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_language',
            field=models.CharField(max_length=80, verbose_name='Язык докуменат'),
        ),
    ]
