# Generated by Django 4.1.7 on 2023-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rights_right_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entities',
            old_name='level',
            new_name='mptt_level',
        ),
        migrations.AlterField(
            model_name='entities',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Родитель'),
        ),
    ]
