# Generated by Django 4.1.7 on 2023-04-04 14:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rename_level_entities_mptt_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Левая'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.entities', verbose_name='Родитель сущности'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Правая'),
        ),
    ]
