# Generated by Django 4.1.7 on 2023-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_entities_lft_alter_entities_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='entities',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='entities',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Уровень вложенности'),
        ),
    ]
