# Generated by Django 4.1.7 on 2023-04-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_entities_lft_alter_entities_rght_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entities',
            old_name='mptt_level',
            new_name='level',
        ),
    ]
