# Generated by Django 4.1.7 on 2023-04-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_rename_mptt_level_entities_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='level',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Уровень'),
        ),
    ]
