# Generated by Django 4.1.5 on 2023-04-08 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_documents_id_alter_entities_id_alter_files_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_url',
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_language',
            field=models.IntegerField(verbose_name='Язык докуменат'),
        ),
        migrations.AlterField(
            model_name='files',
            name='add_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Файлы'),
        ),
    ]
