# Generated by Django 4.1.5 on 2023-04-12 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_remove_files_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='slug',
            field=models.SlugField(default=True, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='relations',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентивикатор отношения'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор пользователя'),
        ),
    ]
