# Generated by Django 4.1.5 on 2023-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_files_slug_alter_relations_id_alter_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='slug',
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%D/', verbose_name='Файлы'),
        ),
    ]
