# Generated by Django 4.1.5 on 2023-04-13 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_remove_files_slug_alter_files_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationsFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентивикатор отношения')),
                ('id_entities', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='system.entities', verbose_name='Идентификатор сущности')),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='system.files', verbose_name='Идентификатор документа')),
            ],
            options={
                'verbose_name': 'Отношения сущностей с файлами',
                'verbose_name_plural': 'Отношения сущностей с файлами',
                'db_table': 'relations_files',
            },
        ),
    ]
