# Generated by Django 4.1.7 on 2023-04-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_relationsfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='entities',
            name='cat_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='system.files', verbose_name='Файл категории'),
        ),
    ]
