# Generated by Django 4.1.7 on 2023-04-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_entities_cat_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_text', models.CharField(max_length=50)),
                ('some_info', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Вспомогательная таблица',
                'verbose_name_plural': 'Вспомогательная таблица',
                'db_table': 'mult_files',
            },
        ),
        migrations.AddField(
            model_name='files',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.multfiles'),
            preserve_default=False,
        ),
    ]
