# Generated by Django 4.1.7 on 2023-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_multfiles_files_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multfiles',
            name='some_info',
        ),
        migrations.AddField(
            model_name='multfiles',
            name='text',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
